# Generated by Django 6.0.6 on 2026-06-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('metropolitan', 'Metropolitan City'), ('sub_metropolitan', 'Sub-Metropolitan City'), ('municipality', 'Municipality'), ('rural', 'Rural Municipality (Gaun Palika)')], default='municipality', max_length=20)),
                ('ward_count', models.PositiveSmallIntegerField(help_text='Official number of wards in this local government unit.')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='api.district')),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='api.municipality'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='api.municipality')),
            ],
            options={
                'ordering': ['municipality', 'number'],
                'unique_together': {('municipality', 'number')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='api.ward'),
        ),
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='api.ward'),
        ),
    ]
